server:
  port: 8080
  timezone: ${SERVER_TIMEZONE:IST}
  servlet:
    context-path: /core

spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/mynextduty_db?currentSchema=core,public
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: core

  hikari:
    pool-name: MyNextDutyCoreHikariPool
    maximum-pool-size: 15
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 20000
    max-lifetime: 1800000

# Logging
logging:
  level:
    com.mynextduty: DEBUG
    org.springframework.security: DEBUG

core:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USERNAME:default}
    password: ${REDIS_PASSWORD:}
    index: ${REDIS_INDEX:0}
    timeout: ${REDIS_TIMEOUT:400000}
  jwt:
    secret: ${JWT_SECRET:}
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION:259200}